print("++++++++++++++++++++++++++++++++++++++")

print("welkom bij je solicitatie voor de positie (Circusdirecteur voor Circus HotelDeBotel)")

print("++++++++++++++++++++++++++++++++++++++")


v1 = int(input('Hoeveel jaar praktijkervaring heeft u met dieren-dressuur?'))
if v1 >= 5:
    print("")
    v2 = input('In bezit van een Diploma MBO-4 ondernemen')
    if v2 == "ja":
        print("")
        v3 = input('heb je  een geldig Vrachtwagen rijbewijs')
        if v3 == "ja":
            print("")
            v4 = input('In bezit van een hoge hoed?')
            if v4 == "ja":
                print("")
                v5a = input('bent u een man of vrouw')
                if v5a == "man":
                    print("")
                    v5b = input('heeft u gezichts beharing')
                    if v5b== "ja":
                        print("")
                        v5c = input('heeft u een snor of een baard')
                        if v5c == "snor":
                            print("")
                            v5d = int(input('hoe breed is je snor?'))
                            if v5d >= 10:
                                print("")
                                v6 = int(input('hoe lang ben je'))
                                if v6 >= 150:
                                    print("")
                                    v7 = int(input('hoe zwaar ben je'))
                                    if v7 >= 90:
                                        print("")
                                        v8 = input('heb je het Certificaat "overleven met gevaarlijk personeel"')
                                        if v8 == "ja":
                                            print("")
                                            print("")
                                            print("++++++++++++++++++++++++++++++++++++++")
                                            print("")
                                            print("")
                                            print("gefeliciteerd je bent aangenomen")
                                            print("")
                                            print("")
                                            print("++++++++++++++++++++++++++++++++++++++")
                                            print("")
                                            print("")
                                        elif v8 == "nee":
                                            print("")
                                            print("")
                                            print("++++++++++++++++++++++++++++++++++++++")
                                            print("")
                                            print("")
                                            print("helaas ben je niet aangenomen je voldoet niet aan de eisen")
                                            print("")
                                            print("")
                                            print("++++++++++++++++++++++++++++++++++++++")
                                            print("")
                                            print("")
                                    elif v7 < 90:
                                        print("")
                                        print("")
                                        print("++++++++++++++++++++++++++++++++++++++")
                                        print("")
                                        print("")
                                        print("helaas ben je niet aangenomen je voldoet niet aan de eisen")
                                        print("")
                                        print("")
                                        print("++++++++++++++++++++++++++++++++++++++")
                                        print("")
                                        print("")
                                elif v6 < 150:
                                    print("")
                                    print("")
                                    print("++++++++++++++++++++++++++++++++++++++")
                                    print("")
                                    print("")
                                    print("helaas ben je niet aangenomen je voldoet niet aan de eisen")
                                    print("")
                                    print("")
                                    print("++++++++++++++++++++++++++++++++++++++")
                                    print("")
                                    print("")
                            elif v5d < 10:
                                print("")
                                print("")
                                print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++")
                                print("")
                                print("")
                                print("helaas ben je niet aangeenomen je voldoet niet aan de eisen")
                                print("")
                                print("")
                        elif v5c == "baard":
                            print("")
                            print("")
                            print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++")
                            print("")
                            print("")
                            print("helaas ben je niet aangeenomen je voldoet niet aan de eisen")
                            print("")
                            print("")
                            print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++")
                            print("")
                            print("")
                    elif v5b == "nee":
                        print("")
                        print("")
                        print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++")
                        print("")
                        print("")
                        print("helaas ben je niet aangeenomen je voldoet niet aan de eisen")
                        print("")
                        print("")
                        print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++")
                        print("")
                        print("")
                elif v5a == "vrouw":
                    print("")
                    haarkleur = input('wat is je haarkleur?')
                    if haarkleur == "rood":
                        print("")
                        haarsoort = input('wat voor soort haar heb je?')
                        if haarsoort == "krullend":
                            print("")
                            haarlengte = input('wat is je haar lengte ')
                            if haarlengte >= 20:
                                print("")
                                v6a = int(input('hoe lang ben je'))
                                if v6a >= 150:
                                    print("")
                                    v7a = int(input('hoe zwaar ben je'))
                                    if v7a >= 90:
                                        print("")
                                        v8a = input('heb je het Certificaat "overleven met gevaarlijk personeel"')
                                        if v8a == "ja":
                                            print("")
                                            print("")
                                            print("++++++++++++++++++++++++++++++++++++++")
                                            print("")
                                            print("")
                                            print("gefeliciteerd je bent aangenomen")
                                            print("")
                                            print("")
                                            print("++++++++++++++++++++++++++++++++++++++")
                                            print("")
                                            print("")
                                        elif v8a == "nee":
                                            print("")
                                            print("")
                                            print("++++++++++++++++++++++++++++++++++++++")
                                            print("")
                                            print("")
                                            print("helaas ben je niet aangenomen je voldoet niet aan de eisen")
                                            print("")
                                            print("")
                                            print("++++++++++++++++++++++++++++++++++++++")
                                            print("")
                                            print("")
                                    elif v7a < 90:
                                        print("")
                                        print("")
                                        print("++++++++++++++++++++++++++++++++++++++")
                                        print("")
                                        print("")
                                        print("helaas ben je niet aangenomen je voldoet niet aan de eisen")
                                        print("")
                                        print("")
                                        print("++++++++++++++++++++++++++++++++++++++")
                                        print("")
                                        print("")
                                elif v6a < 150:
                                    print("")
                                    print("")
                                    print("++++++++++++++++++++++++++++++++++++++")
                                    print("")
                                    print("")
                                    print("helaas ben je niet aangenomen je voldoet niet aan de eisen")
                                    print("")
                                    print("")
                                    print("++++++++++++++++++++++++++++++++++++++")
                                    print("")
                                    print("")
                            elif v5d < 10:
                                print("")
                                print("")
                                print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++")
                                print("")
                                print("")
                                print("helaas ben je niet aangeenomen je voldoet niet aan de eisen")
                                print("")
                                print("")
                        elif v5c == "baard":
                            print("")
                            print("")
                            print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++")
                            print("")
                            print("")
                            print("helaas ben je niet aangeenomen je voldoet niet aan de eisen")
                            print("")
                            print("")
                            print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++")
                            print("")
                            print("")
                    elif v5b == "nee":
                        print("")
                        print("")
                        print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++")
                        print("")
                        print("")
                        print("helaas ben je niet aangeenomen je voldoet niet aan de eisen")
                        print("")
                        print("")
                        print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++")
                        print("")
                        print("")






            elif v4 == "nee":
                print("")
                print("")
                print("++++++++++++++++++++++++++++++++++++++++++++++++++++")
                print("")
                print("")
                print("helaas ben je niet aangenomen je voldoet niet aan de eisen")
                print("")
                print("")
        elif v3 == "nee":
            print("")
            print("")
            print("++++++++++++++++++++++++++++++++++++++++++++++++++++")
            print("")
            print("")
            print("helaas ben je niet aangenomen je voldoet niet aan de eisen")
            print("")
            print("")
    elif v2 == "nee":
                print("")
                print("")
                print("++++++++++++++++++++++++++++++++++++++++++++++++++++")
                print("")
                print("")
                print("helaas ben je niet aangenomen je voldoet niet aan de eisen")
                print("")
                print("")
elif v1 < 5:
    print("")
    print("")
    print("++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print("")
    print("")
    print("helaas ben je niet aangenomen je voldoet niet aan de eisen")
    print("")
    print("")